[[news]]
date = "2026/05/14"
content = "I have been recognized as a Gold Reviewer (top 25%) by ICML 2026 🎉"

[[news]]
date = "2026/05/04"
content = "I got the position of UM Postdoctoral Fellow (UMPF) at the University of Macau (UM) under the UM Talent Programme 🎉"

[[news]]
date = "2025/10/17"
content = "I have been selected as a Top Reviewer (top 8%) by NeurIPS 2025 🎉"

[[news]]
date = "2025/07/16"
content = "One paper was accepted by TIP 🎉"

[[news]]
date = "2025/04/29"
content = "One paper was accepted by IJCAI 2025 🎉"
